<?php
/**
 * @file
 * Code for the Ding Event Rooms feature.
 */

include_once 'ding_event_rooms.features.inc';

/**
 * Implements hook_post_features_revert().
 */
function ding_event_rooms_post_features_revert($component) {
  /**
   * Every time when this feature will be reverted 'field_ding_event_rooms'
   * field will be placed into the correct fieldgroup.
   */

  // Positioning field to event node form's tagging group.
  $groups = field_group_read_groups(
    array(
      'entity_type' => 'node',
      'bundle' => 'ding_event',
      'mode' => 'form'
    )
  );

  $group_content = $groups['node']['ding_event']['form']['group_ding_event_date_loc_price'];
  $group_content->children[] = 'field_ding_event_rooms';
  field_group_group_save($group_content);

  // Positioning field to left group of default display of event node.
  $display_groups = field_group_read_groups(
    array(
      'entity_type' => 'node',
      'bundle' => 'ding_event',
      'mode' => 'default',
    )
  );

  $group_content = $display_groups['node']['ding_event']['default']['group_left'];
  $group_content->children[] = 'field_ding_event_rooms';

  field_group_group_save($group_content);

  // Because of pushing out of ding_event_rooms field from ding_event's tagging
  // fieldgroup, set a random value in variable exported into this module in
  // order to have this feature permanently overriden so we can revert this feature.
  variable_set('ding_event_rooms_random', rand());
}

/**
 * Implements hook_preprocess_field().
 */
function ding_event_rooms_preprocess_field(&$variables) {
  /*
   * Pass 'field_ding_event_rooms' renderable array to be customly rendered
   * in custom 'field_og_group_ref' field template.
   */
  if ($variables['element']['#field_name'] == 'og_group_ref') {
    $node = $variables['element']['#object'];
    $rooms = field_view_field('node', $node, 'field_ding_event_rooms');
    $rooms['#label_display'] = 'inline';
    $variables['rooms_field'] = $rooms;
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function ding_event_rooms_theme_registry_alter(&$theme_registry) {
  // Defined path to the current module.
  $path = drupal_get_path('module', 'ding_event_rooms');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}
